name: Feature request
description: Suggest an idea
title: "[Feature]: "
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: Problem to solve
  - type: textarea
    attributes:
      label: Proposed solution
